/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class vn_edu_hust_student_linhdt_project_OpenCvClass */
using namespace cv;
#ifndef _Included_vn_edu_hust_student_linhdt_project_OpenCvClass
#define _Included_vn_edu_hust_student_linhdt_project_OpenCvClass
#ifdef __cplusplus
extern "C" {
#endif

void DetectCat(Mat& frame);
void DetectDog(Mat& frame);
void DetectBuffalo(Mat& frame);
void DetectPeople(Mat& frame);
void DetectPig(Mat& frame);
void DetectChicken(Mat& frame);

/*
 * Class:     vn_edu_hust_student_linhdt_project_OpenCvClass
 * Method:    catDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vn_edu_hust_student_linhdt_project_OpenCvClass_catDetection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vn_edu_hust_student_linhdt_project_OpenCvClass
 * Method:    dogDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vn_edu_hust_student_linhdt_project_OpenCvClass_dogDetection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vn_edu_hust_student_linhdt_project_OpenCvClass
 * Method:    buffaloDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vn_edu_hust_student_linhdt_project_OpenCvClass_buffaloDetection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vn_edu_hust_student_linhdt_project_OpenCvClass
 * Method:    peopleDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vn_edu_hust_student_linhdt_project_OpenCvClass_peopleDetection
  (JNIEnv *, jclass, jlong);

//Pig
JNIEXPORT void JNICALL Java_vn_edu_hust_student_linhdt_project_OpenCvClass_pigDetection
  (JNIEnv *, jclass, jlong);

//Chicken
JNIEXPORT void JNICALL Java_vn_edu_hust_student_linhdt_project_OpenCvClass_chickenDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
